### ISSUE TITLE
"ambiguous python shebang" when build rpm package

### ISSUE THREAD

**Issue by banjiaojuhao** [LinearTapeFileSystem/ltfs#424]
**Describe the bug**

[error ](https://github.com/banjiaojuhao/rpm-ltfs/actions/runs/6022566762/job/16337564602#step:5:1569)produced when build rpm package in rocky linux 8:
> ambiguous python shebang in /usr/bin/ltfs_ordered_copy: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.

**To Reproduce**
the [github action config](https://github.com/banjiaojuhao/rpm-ltfs/blob/master/.github/workflows/build-rpm.yml) like below:
```yaml
name: build centos 8 stream rpm

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/rockylinux:8
    steps:
    - uses: actions/checkout@v2
 
    - name: intall deps
      run: |
        yum -y update && yum -y upgrade
        yum -y install automake autoconf libtool make icu libicu-devel libxml2-devel libuuid-devel fuse-devel net-snmp-devel git python3 wget rpm-build rpmdevtools yum-utils
        alternatives --set python /usr/bin/python3
 
    - name: build-rpm
      run: |
        rpmdev-setuptree
        cp ltfs.spec ~/rpmbuild/SPECS/
        wget -O ~/rpmbuild/SOURCES/ltfs-2.4.4.0.tar.gz https://github.com/LinearTapeFileSystem/ltfs/archive/v2.4.4.0-10470/ltfs-2.4.4.0.tar.gz
        yum-builddep -y ~/rpmbuild/SPECS/ltfs.spec
        rpmbuild -ba ~/rpmbuild/SPECS/ltfs.spec


    - name: Upload bin directory
      uses: actions/upload-artifact@main
      with:
        name: ltfs-2.4.4.0-10470.x86_64.rpm
        path: /github/home/rpmbuild/RPMS/x86_64/ltfs-2.4.4.0-10470.x86_64.rpm
```

**Suggestion**
change [this line](https://github.com/LinearTapeFileSystem/ltfs/blob/7681d4d53f45def3a682c3752235a2ad7dfeb435/src/utils/ltfs_ordered_copy#L1) to:
```shell
#!/usr/bin/env python3
```
